#!/usr/bin/env bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.default"; set +a

SECRETS_EJSON_FILE="${SECRETS_EJSON_FILE:-secrets.prod.ejson}"
secrets_ejson_path="${script_dir}/manifests/${SECRETS_EJSON_FILE}"

secrets_manifest_path="${script_dir}/manifests/${K8S_SECRETS_FILE}"

# convert the ejson file to a manifest
echo "Converting ejson secrets file to manifest..."
"${script_dir}/convert-ejson-to-manifest" ${secrets_ejson_path} ${secrets_manifest_path} ${K8S_SECRETS_NAME} ${K8S_NAMESPACE}

# Check that the secrets file exists.
if [[ ! -f "${secrets_manifest_path}" ]]; then
  echo "Secrets file not found at ${secrets_manifest_path}"
  exit 1
fi

# Deploy the k8s secrets.
echo "Deploying k8s secrets..."
envsubst < "${secrets_manifest_path}" | kubectl apply -f -
echo

